UH-StudentServices/mystudies-myteaching-backend

app/src/main/java/fi/helsinki/opintoni/cache/CacheConstants.java
app/src/main/java/fi/helsinki/opintoni/dto/LearningOpportunityDto.java
app/src/main/java/fi/helsinki/opintoni/integration/oodi/OodiLearningOpportunity.java
app/src/main/java/fi/helsinki/opintoni/integration/oodi/OodiRestClient.java
app/src/main/java/fi/helsinki/opintoni/integration/oodi/mock/OodiMockClient.java
app/src/main/java/fi/helsinki/opintoni/service/CourseService.java
app/src/main/java/fi/helsinki/opintoni/service/converter/LearningOpportunityConverter.java
app/src/main/java/fi/helsinki/opintoni/web/rest/privateapi/CourseResource.java
app/src/main/resources/sampledata/oodi/learningopportunity_a.json
app/src/main/resources/sampledata/oodi/learningopportunity_b.json
app/src/test/java/fi/helsinki/opintoni/SpringTest.java
app/src/test/java/fi/helsinki/opintoni/server/OodiServer.java
app/src/test/java/fi/helsinki/opintoni/web/requestchain/OodiCourseNamesRequestChain.java
app/src/test/java/fi/helsinki/opintoni/web/rest/privateapi/CourseResourceTest.java
app/src/test/resources/sampledata/oodi/learningopportunity_a.json
app/src/test/resources/sampledata/oodi/learningopportunity_b.json

A proxy to get course names from the Oodi.

Backend for new Leiki based recommendations.

---

app/src/main/java/fi/helsinki/opintoni/integration/leiki/LeikiRestClient.java
app/src/test/java/fi/helsinki/opintoni/server/LeikiServer.java

The enddate is hard coded and needed 2222-12-31T00:00:00+0300.

Added timestamps to Leiki server calls.

---

app/src/main/java/fi/helsinki/opintoni/integration/flamma/FlammaRestClient.java
app/src/main/resources/config/application.yml
app/src/test/java/fi/helsinki/opintoni/server/FlammaServer.java
app/src/test/resources/config/application.yml

Tässä muutettu vain syötteiden osoitteet. Halutaankohan ne kuitenkaan noin kovakoodatuksi, vai olisiko hyvä ajatus ottaa syötteiden osoitteet application.ymlistä?

OO-947 change students' news source feed

---

app/src/main/java/fi/helsinki/opintoni/service/news/NewsService.java
app/src/test/java/fi/helsinki/opintoni/web/rest/privateapi/NewsResourceTest.java

Fiksi ongelmaan, en saanut aikaiseksi testiä, jossa se olis toistunut niin sellaista ei nyt ole :(

OO-992 fix duplicate newsfeed items

---

app/src/main/java/fi/helsinki/opintoni/dto/EventDto.java
app/src/main/java/fi/helsinki/opintoni/service/CalendarService.java
app/src/test/java/fi/helsinki/opintoni/dto/EventDtoTest.java
app/src/test/java/fi/helsinki/opintoni/web/rest/privateapi/EnrollmentResourceGetStudentEventsTest.java
app/src/test/java/fi/helsinki/opintoni/web/rest/privateapi/EnrollmentResourceGetTeacherEventsTest.java

Vaihdettu metodin nimi ja korjattu testit.

Changed method name so that change doesn't affect other event APIs

---

app/src/main/java/fi/helsinki/opintoni/exception/GlobalExceptionHandlers.java
app/src/test/java/fi/helsinki/opintoni/web/rest/privateapi/OfficeHoursResourceTest.java

OO-1085 map constraintviolationexception to 4xx status

---

app/src/main/java/fi/helsinki/opintoni/web/rest/privateapi/FavoriteResource.java
app/src/test/java/fi/helsinki/opintoni/web/rest/privateapi/FavoriteResourceTest.java

Poistettu RSS haku backendistä

Removed RSS feed endpoint

---

app/src/main/java/fi/helsinki/opintoni/domain/portfolio/PortfolioKeyword.java

Added identity generation strategy

---

app/src/main/java/fi/helsinki/opintoni/service/EventService.java
app/src/main/resources/config/application-local-dev.yml
app/src/test/resources/config/application.yml
app/src/test/resources/sampledata/coursepage/course.json

- dropping out study events without start date
- disabled logging of hibernate sql statements

OO-1144 Opintoni ei hae opiskelijan kursseja ja näyttää virheilmoituksen

---

app/src/main/java/fi/helsinki/opintoni/repository/TodoItemRepository.java
app/src/main/java/fi/helsinki/opintoni/service/TodoItemService.java
app/src/main/java/fi/helsinki/opintoni/web/rest/privateapi/TodoItemResource.java
app/src/test/java/fi/helsinki/opintoni/web/rest/privateapi/TodoItemResourceTest.java

- now returning all todo items instead of dropping those that are older than 4 months

OO-1129 Estetään vanhojen merkintöjen katoaminen tehtävälistalta

---

app/src/main/java/fi/helsinki/opintoni/web/rest/publicapi/ConfigurationResource.java
app/src/main/resources/config/application-demo.yml
app/src/main/resources/config/application-dev.yml
app/src/main/resources/config/application-local-dev.yml
app/src/main/resources/config/application-prod.yml
app/src/main/resources/config/application-qa.yml

- Added event tracking to multiple user actions.
- Added page tracking to app init.

OO-551 Opiskelijaportfolio googleanalyticsiin

---

app/src/main/java/fi/helsinki/opintoni/domain/portfolio/SomeLink.java

- Added frontend validation to contact information email and social media link url fields.
- To support validation, editLink directive no longer switches out of edit mode if onExitEdit returns false.
- Social media links now have a default base url to indicate the required format to the user. Used as a placeholder.
- Added LinkedIn social media type.
- Adjusted social media link icon layout for a more visually pleasing experience.

OO-1156 Portfolion yhteystietojen käytettävyysparannuksia

---

app/src/main/java/fi/helsinki/opintoni/domain/portfolio/Sample.java
app/src/main/java/fi/helsinki/opintoni/dto/portfolio/SampleDto.java
app/src/main/java/fi/helsinki/opintoni/service/converter/SampleConverter.java
app/src/main/java/fi/helsinki/opintoni/service/portfolio/SampleService.java
app/src/main/java/fi/helsinki/opintoni/web/rest/privateapi/portfolio/sample/UpdateSample.java
app/src/main/resources/config/liquibase/changelog/initial_schema.xml
app/src/test/java/fi/helsinki/opintoni/web/rest/privateapi/portfolio/PrivateSampleResourceTest.java

- Lisätty migraatio, joka lisää samplejen (ennen pakollisen) urlin descriptionin loppuun rivinvaihtojen ympäröimänä (frontti leipoo siitä linkin)
- Poistettu sampleista url-kenttä

OO-1161 - Portfolion työnäyte-osio

---

src/main/java/fi/helsinki/opintoni/web/rest/privateapi/portfolio/FileUploadResponse.java
src/test/java/fi/helsinki/opintoni/web/rest/privateapi/portfolio/PrivateFilesResourceTest.java

- Removed an extra slash from the URL created upon file upload.

OO-1104 Tiedoston upload - Front-end (Portfolio tiedostot)

---

src/main/java/fi/helsinki/opintoni/dto/OptimeExtrasDto.java
src/main/java/fi/helsinki/opintoni/resolver/LocationResolver.java
src/main/java/fi/helsinki/opintoni/service/converter/EventConverter.java
src/test/java/fi/helsinki/opintoni/resolver/LocationResolverTest.java

Show optime roomNotes in event's Location field

Create new locations when oodiEvent contains optime roomNotes

---

src/main/java/fi/helsinki/opintoni/integration/unisport/UnisportRestClient.java
src/main/resources/config/application-demo.yml
src/main/resources/config/application-prod.yml
src/main/resources/config/application-qa.yml
src/main/resources/config/application.yml
src/test/java/fi/helsinki/opintoni/server/UnisportServer.java

- Changed UniSport API addresses - UniSport now have a test environment.

OO-1314 UniSportin API-osoite pitää muuttaa

---

src/main/resources/config/application.yml

- Changed RSS feed URLs for the news carousel.

OO-1323 Tiedotefeedit uudesta Flammasta

---

README.md
src/main/resources/config/liquibase/changelog/initial_schema.xml

- Added an index to localization.localized_text_id
- Simplified instructions in README.

OO-1465 Nopeutetaan kutsua /api/private/v1/notifications

---

src/main/java/fi/helsinki/opintoni/integration/studyregistry/sisu/mock/SisuMockClient.java

Sisu mock data oli puutteellista. Lisätty mock course unit realisationiin organisaatiot, activity period, id ja study group setit.

OO-1494 e2e test don't pass

---

README.md
src/main/java/fi/helsinki/opintoni/config/StudyRegistryConfiguration.java
src/main/java/fi/helsinki/opintoni/integration/studyregistry/sisu/SisuGraphQLClient.java
src/main/resources/config/application.yml
src/test/java/fi/helsinki/opintoni/integration/studyregistry/sisu/SisuGraphQLClientTest.java
src/test/resources/config/application.yml

- Removed sisuApiPath configuration parameter, as the value is always /graphql.
- Added sisuApiKey configuration parameter.
- Changed sisu.baseUrl to point to API GW.
- Added API GW cert and key configurations and Ansible commands to add them into the key store.

https://jira.it.helsinki.fi/browse/OO-1500 OO käyttämään Sisu-APIa
